DROP TABLE IF EXISTS strenght;
DROP TABLE IF EXISTS endurance;

CREATE TABLE strenght(
    id integer generated by default as identity,
    exercise TEXT,
    reps varchar(32),
    work_id INT,
    week_id INT
);

CREATE TABLE endurance(
    id integer generated by default as identity,
    exercise TEXT,
    reps varchar(32),
    superset INT,
    work_id INT NOT NULL,
    week_id INT NOT NULL
);